### ISSUE TITLE
Admin UI Failed to Open

### ISSUE THREAD

**Issue by joeybellerose** [FarazPatankar/pocketbase#1]
I was trying to get this template working on Railway and kept getting the following error when trying to navigate to the Admin UI:

`{"code":404,"message":"Not Found.","data":{}}`

I saw in the [docs](https://pocketbase.io/docs/) to go to port 8090.  I only saw port 8080 opened on the [Dockerfile](https://github.com/FarazPatankar/pocketbase/blob/main/Dockerfile#L13).  Not sure if that matters.

What do I need to do differently to see the Admin UI?

**Comment by FarazPatankar** [comment]
It's on the `_` path, did you try that?

<img width="874" alt="CleanShot 2023-07-08 at 23 13 44@2x" src="https://github.com/FarazPatankar/pocketbase/assets/10681116/5be7338e-5e45-4fda-afb9-fc79d4857692">

**Comment by joeybellerose** [comment]
Yep, that was my mistake.  Thanks for the help!
